### ISSUE TITLE
Google nearby api 12.0.1 with android things stable release 1.0 throws 8007 STATUS_BLUETOOTH_ERROR

### ISSUE THREAD

**Issue by KoustuvGanguly** [androidthings/robocar#2]
I am using NearBy 2.0 API version `'com.google.android.gms:play-services-nearby:12.0.1' `with android things` 'com.google.android.things:androidthings:1.0' `to create a smart home app, but previously upto 8th may it was working fine with the build downloaded from android things console , but from yesterday it is throwing `com.google.android.gms.common.api.ApiException:8007 STATUS_BLUETOOTH_ERROR`. when i am starting advertisement or discovery whichever maybe. But if I use the previous build(image with apk) of 8th may it is working fine . I tried with that old apk also like new os image with old apk , found not working. In logcat i found it is unable to start listening for incoming connections. I searched SO and google a lot but no solution worked. Even followed this [https://stackoverflow.com/questions/46036191/error-codes-in-nearby-connections-2-0/46328410](url) but no luck. I am using Raspberry PI 3 model B. Help!!

**Comment by KoustuvGanguly** [comment]
Finally I got it working , actually when I was configuring the hardware during the build preparation in android things console there I used Starter Kit configuration which by default configured `UART` as `UART0 (disables Bluetooth)` , hence the exception it was throwing `com.google.android.gms.common.api.ApiException:8007 STATUS_BLUETOOTH_ERROR`. during init of nearby where I was starting advertisement. So the fix is change the configuration of `UART` to `MINIUART` in android things console and create the build.

**Comment by AbhishekTripathi1289** [comment]
Hello brother,
I am facing the same bluetooth error(8007) whenever my discoverer sends connection request to the advertiser using Nearby.Connections.requestConnection() method.
Though my advertiser is advetising successfully and discoverer is able to discover the advertiser.
Also, can you explain what UART and MINIUART is?

**Comment by Chinedu25** [comment]
facing same issue any solution?
